### ISSUE TITLE
pod model do not support volume of hostPath type

### ISSUE THREAD

**Issue by xufei96** [fiaas/k8s#40]
I met an issue, when run Deployment.get('deployment-name','namespace-name') and deployment.save() ,  deployment-name's hostPath volume lost.

I support to add following codes to support volume of hostPath type on definition of deployment.

code file: k8s/models/pod.py

class HostPathVolumeSource(Model):
    path = Field(six.text_type)

class Volume(Model):
    name = Field(six.text_type)
    secret = Field(SecretVolumeSource)
    configMap = Field(ConfigMapVolumeSource)
    emptyDir = Field(EmptyDirVolumeSource)
    hostPath = Field(HostPathVolumeSource)

I have tested these code work fine for hostPath volume.

**Comment by oyvindio** [comment]
Yes you are right, those fields seem to be missing from the model definition. Do you want to do a pull request with your changes?
